spring.application.name=TP2

# Base H2 en mémoire
spring.datasource.url=jdbc:h2:mem:products-db
spring.datasource.username=sa
spring.datasource.password=

# Correction : ddl-auto (pas ddl-uto)
spring.jpa.hibernate.ddl-auto=update

# Port du serveur
server.port=8084

# Correction : true (pas tru)
spring.h2.console.enabled=true